#!C:\Users\Ahtesham Iqbal\Downloads\Smart-Attendance-System-master\env\Scripts\python.exe
import pcsv
from jtutils import fix_broken_pipe

if __name__ == "__main__":
    fix_broken_pipe()
    pcsv.pcsv()
